# -*- coding: utf-8 -*-
"""COTIVITI _ASSESSMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifFxqxZGlEHQvmi0vEOlMMCepec1vTV3
"""

import random
import math
import json
from datetime import date, timedelta
from collections import defaultdict

""" 1. Synthetic Data Generation"""

random.seed(42)

PROVIDERS = {
    "PRV-001": "General Practice – Riverside Clinic",
    "PRV-002": "Cardiology Associates",
    "PRV-003": "Orthopedics of the Valley",
    "PRV-004": "Sunrise Family Medicine",
    "PRV-005": "FraudAlert Specialty Group",   # injected bad actor
}

CPT_CODES = {
    "99213": ("Office Visit – Moderate", 110),
    "93000": ("ECG w/ Interpretation", 75),
    "27447": ("Total Knee Arthroplasty", 4200),
    "99232": ("Subsequent Hospital Care", 145),
    "99215": ("Office Visit – High Complexity", 210),
}

def generate_claims(weeks=26):
    """Generate synthetic weekly claim counts per provider, with anomalies injected."""
    start = date(2025, 1, 6)
    timeline = [start + timedelta(weeks=w) for w in range(weeks)]
    claims = {}

    for pid, pname in PROVIDERS.items():
        base = random.randint(40, 160)           # weekly baseline
        drift = random.uniform(-0.5, 1.2)        # slow trend
        noise_sd = base * 0.12                   # ~12% noise

        weekly = []
        for w, week_date in enumerate(timeline):
            count = base + drift * w + random.gauss(0, noise_sd)
            count = max(1, round(count))

            # Inject anomaly: PRV-005 spikes in weeks 18-22
            if pid == "PRV-005" and 18 <= w <= 22:
                count = round(count * random.uniform(3.5, 5.2))

            # Random isolated spike for others (1 in 15 chance)
            if pid != "PRV-005" and random.random() < 0.067:
                count = round(count * random.uniform(1.8, 2.4))

            weekly.append({"week": week_date.isoformat(), "count": count})

        claims[pid] = {"name": pname, "weekly": weekly}

    return claims, timeline

"""2. Anomaly Detection Agent"""

def zscore_anomalies(series, threshold=2.5):
    """Flag weeks where claim count deviates > threshold standard deviations."""
    values = [p["count"] for p in series]
    n = len(values)
    mean = sum(values) / n
    sd = math.sqrt(sum((v - mean) ** 2 for v in values) / n)
    if sd == 0:
        return []
    flags = []
    for i, p in enumerate(series):
        z = (p["count"] - mean) / sd
        if abs(z) > threshold:
            flags.append({"week": p["week"], "count": p["count"],
                          "z_score": round(z, 2), "mean": round(mean, 1), "sd": round(sd, 1)})
    return flags

"""3. Classifier Agent"""

def classify_anomaly(pid, flag, provider_name):
    """
    Mimics an agentic reasoning step: given an anomaly flag,
    produce a structured risk classification and next-action recommendation.
    """
    z = flag["z_score"]
    ratio = flag["count"] / flag["mean"] if flag["mean"] > 0 else 0

    if z >= 4.0 or ratio >= 4.0:
        risk = "HIGH"
        action = "Escalate to FWA (Fraud, Waste & Abuse) team for full audit"
    elif z >= 3.0 or ratio >= 2.5:
        risk = "MEDIUM"
        action = "Flag for prepayment clinical review; request supporting documentation"
    else:
        risk = "LOW"
        action = "Monitor for recurrence; log in anomaly registry"

    return {
        "provider_id": pid,
        "provider_name": provider_name,
        "week": flag["week"],
        "claim_count": flag["count"],
        "expected_mean": flag["mean"],
        "z_score": flag["z_score"],
        "ratio_to_mean": round(ratio, 2),
        "risk_level": risk,
        "recommended_action": action,
    }

"""4. Reporter Agent (ASCII Dashboard)"""

BAR_WIDTH = 40

def sparkline(series, width=50):
    """Mini ASCII sparkline of weekly claim counts."""
    values = [p["count"] for p in series]
    lo, hi = min(values), max(values)
    chars = " ▁▂▃▄▅▆▇█"
    if hi == lo:
        return "─" * width
    line = ""
    for v in values[-width:]:
        idx = round((v - lo) / (hi - lo) * (len(chars) - 1))
        line += chars[idx]
    return line

def bar(value, max_value, width=BAR_WIDTH):
    filled = round(value / max_value * width) if max_value else 0
    return "█" * filled + "░" * (width - filled)

def print_report(claims, all_findings):
    SEP = "═" * 72
    sep = "─" * 72

    print(f"\n{SEP}")
    print("  COTIVITI POC — AGENTIC CLAIMS ANOMALY DETECTION DASHBOARD")
    print(f"  Analysis period: 26 weeks  |  Providers monitored: {len(claims)}")
    print(SEP)

    # Provider summary table
    print(f"\n{'PROVIDER':<36} {'TOTAL CLAIMS':>12} {'ANOMALIES':>10} {'MAX Z':>8}")
    print(sep)
    max_total = max(sum(p["count"] for p in d["weekly"]) for d in claims.values())
    for pid, data in claims.items():
        total = sum(p["count"] for p in data["weekly"])
        findings = [f for f in all_findings if f["provider_id"] == pid]
        max_z = max((f["z_score"] for f in findings), default=0.0)
        flag = "  ⚠ ALERT" if any(f["risk_level"] == "HIGH" for f in findings) else ""
        print(f"  {data['name']:<34} {total:>12,} {len(findings):>10} {max_z:>8.2f}{flag}")

    # Sparklines
    print(f"\n{'WEEKLY CLAIM TREND (26 weeks, left=Jan 2025)':}")
    print(sep)
    for pid, data in claims.items():
        spark = sparkline(data["weekly"], width=50)
        print(f"  {data['name'][:34]:<34} {spark}")

    # Detailed findings
    print(f"\n{SEP}")
    print("  ANOMALY FINDINGS — AGENTIC CLASSIFICATION RESULTS")
    print(SEP)

    if not all_findings:
        print("  No anomalies detected above threshold.\n")
    else:
        for f in sorted(all_findings, key=lambda x: -x["z_score"]):
            risk_label = {"HIGH": "[ HIGH RISK ]", "MEDIUM": "[ MED  RISK ]", "LOW": "[ LOW  RISK ]"}[f["risk_level"]]
            print(f"\n  {risk_label}  {f['provider_name']}")
            print(f"  Week: {f['week']}  |  Claims: {f['claim_count']:,}  |  Expected ~{f['expected_mean']:.0f}  |  Ratio: {f['ratio_to_mean']:.1f}x  |  Z={f['z_score']}")
            print(f"  ► Action: {f['recommended_action']}")
            print(f"  {'─'*66}")

    # Summary counts
    high = sum(1 for f in all_findings if f["risk_level"] == "HIGH")
    med  = sum(1 for f in all_findings if f["risk_level"] == "MEDIUM")
    low  = sum(1 for f in all_findings if f["risk_level"] == "LOW")
    print(f"\n  SUMMARY: {len(all_findings)} anomalies detected — HIGH: {high}  MEDIUM: {med}  LOW: {low}")
    print(f"{SEP}\n")

"""5. Agentic Orchestrator"""

def run_agentic_pipeline():
    print("\n[AGENT] Initializing Claims Anomaly Detection Pipeline...")

    # Step 1 — Data ingestion
    print("[AGENT] Step 1/3 — Generating synthetic claims data (26 weeks, 5 providers)...")
    claims, timeline = generate_claims(weeks=26)

    # Step 2 — Detection agent
    print("[AGENT] Step 2/3 — Running time-series anomaly detection (Z-score, threshold=2.5σ)...")
    all_flags = {}
    for pid, data in claims.items():
        flags = zscore_anomalies(data["weekly"], threshold=2.5)
        all_flags[pid] = flags
    total_flags = sum(len(v) for v in all_flags.values())
    print(f"          → {total_flags} anomalous weeks flagged across all providers.")

    # Step 3 — Classifier agent
    print("[AGENT] Step 3/3 — Classifying anomalies and generating recommendations...")
    all_findings = []
    for pid, flags in all_flags.items():
        provider_name = claims[pid]["name"]
        for flag in flags:
            finding = classify_anomaly(pid, flag, provider_name)
            all_findings.append(finding)

    # Step 4 — Reporter agent
    print_report(claims, all_findings)

    # Step 5 — Export JSON findings
    output_path = "/content/anomaly_findings.json"
    with open(output_path, "w") as f:
        json.dump(all_findings, f, indent=2)
    print(f"  [OUTPUT] Structured findings exported → {output_path}\n")

if __name__ == "__main__":
    run_agentic_pipeline()